### ISSUE TITLE
Angular 1.3.x support

### ISSUE THREAD

**Issue by hirtenfelder** [paulocaldeira17/angular-websql#22]
Hi

I wanted to try out the angular-websql but got an error with bower install:

*ECONFLICT Unable to find suitable version for angular*

I use Angular 1.3.13. Seems that the angular-websql runs only with Angular 1.2.x. 
Is there an update planned to support newer versions of angular?

Thanks

**Comment by paulocaldeira17** [comment]
Hi @hirtenfelder, this issue was solved with #25 merge request.
