### ISSUE TITLE
Operators

### ISSUE THREAD

**Issue by sidonaldson** [paulocaldeira17/angular-websql#27]
Could you provide an example of different types of oporators?

I've tried 
```db.select('categories', {
                        "supcat_id": {
                            "value": '<5'
                        }
                    }).then(function(results) {
                        console.log(results.rows);
                    })```
but the query is always `SELECT * FROM categories WHERE supcat_id = ?;` with no results.

**Comment by paulocaldeira17** [comment]
Hi @sidonaldson,

I only have an example of operators in [update method](https://github.com/paulocaldeira17/angular-websql#update) but you can use operators like this:

```
db.select('categories', {
    "supcat_id": { 
        "operator": '<', // also you can use: '=', '>=', '<=' and 'LIKE'
        "value": '5',
    }
}).then(function(results) { 
    console.log(results.rows); 
});
```

That solves your problem?

**Comment by sidonaldson** [comment]
It sure does! I just spotted that by searching closed issues.
Would it be possible to amend the docs just in case someone else overlooks that method, i only missed it as I hadn't got as far as using the update method yet. Thanks. Loving the work so far
